name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
    
      matrix:
        node-version: [20.11.1]
        
    env: 
      PORT: ${{secrets.PORT}}
      DATABASE_URI: ${{secrets.DATABASE_URI}}
      PAYLOAD_SECRET: ${{secrets.PAYLOAD_SECRET}}
      PAYLOAD_PUBLIC_SERVER_URL: ${{secrets.PAYLOAD_PUBLIC_SERVER_URL}}
      NEXT_PUBLIC_SERVER_URL: ${{secrets.NEXT_PUBLIC_SERVER_URL}}
      PAYLOAD_PUBLIC_DRAFT_SECRE: ${{secrets.PAYLOAD_PUBLIC_DRAFT_SECRE}}
      NEXT_PRIVATE_DRAFT_SECRET: ${{secrets.NEXT_PRIVATE_DRAFT_SECRET}}
      REVALIDATION_KEY: ${{secrets.REVALIDATION_KEY}}
      NEXT_PRIVATE_REVALIDATION_KEY: ${{secrets.NEXT_PRIVATE_REVALIDATION_KEY}}
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: export NODE_ENV=production  
    - run: npm run build:payload 
    - run: npm run build:server
    - run: npm run copyfiles
    - run: npm run build:next
    - run: npm run serve
